all:
	gcc -o rush-00 rush-00.c conv.c ft_putchar.c
	gcc -o rush-01 rush-01.c conv.c ft_putchar.c
	gcc -o rush-02 rush-02.c conv.c ft_putchar.c
	gcc -o rush-03 rush-03.c conv.c ft_putchar.c
	gcc -o rush-04 rush-04.c conv.c ft_putchar.c
	gcc -o rush-2 test.c conv.c ft_putchar.c
